name: Release gocapture-cli

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: gocapture-cli ${{ github.ref }}
          draft: false
          prerelease: false
  linuxbuild:
    name: build linux version
    needs: release
    runs-on: ubuntu-latest
    env:
      PCAPV: 1.10.1
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y libpcap-dev gcc bison flex gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build linux amd64 version
        run: |
          rm -f nac.manifest nac.syso
          wget http://www.tcpdump.org/release/libpcap-$PCAPV.tar.gz
          tar -zxvf libpcap-$PCAPV.tar.gz
          cd libpcap-$PCAPV
          ./configure --with-pcap=linux
          make
          cd ..
          CGO_ENABLED=1 CGO_LDFLAGS="-L/home/runner/work/gocapture/gocapture/libpcap-$PCAPV -static" go build -o gocapturecli_linux_amd64 .
      - name: build linux arm version
        run: |
          cd libpcap-$PCAPV
          make clean
          export CC=arm-linux-gnueabi-gcc
          ./configure --host=arm-linux --with-pcap=linux
          make
          cd ..
          env CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm CGO_LDFLAGS="-L/home/runner/work/gocapture/gocapture/libpcap-$PCAPV -static" go build -o gocapturecli_linux_arm .
      - name: build linux arm64 version
        run: |
          cd libpcap-$PCAPV
          make clean
          export CC=aarch64-linux-gnu-gcc
          ./configure --host=aarch64-linux --with-pcap=linux
          make
          cd ..
          env CC=aarch64-linux-gnu-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CGO_LDFLAGS="-L/home/runner/work/gocapture/gocapture/libpcap-$PCAPV -static" go build -o gocapturecli_linux_arm64
      - name: upload amd64 version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: gocapturecli_linux_amd64
          asset_name: gocapturecli_linux_amd64
          asset_content_type: application/gzip
      - name: upload arm64 version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: gocapturecli_linux_arm64
          asset_name: gocapturecli_linux_arm64
          asset_content_type: application/gzip
      - name: upload arm version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: gocapturecli_linux_arm
          asset_name: gocapturecli_linux_arm
          asset_content_type: application/gzip
  windowsbuild:
    name: build windows version
    runs-on: windows-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build windows version
        run: go build -v -o gocapturecli_windows.exe ./...
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: gocapture-cli.exe
          asset_name: gocapture-cli.exe
          asset_content_type: application/gzip
